nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "8090:80"
php:
  image: chialab/php:7.2-fpm
  volumes:
    - ./:/var/www/html/app
  working_dir: /var/www/html/app/public
  command: php-fpm
  links:
    - db
  environment:
    DB_USERNAME: shorturl
    DB_PASSWORD: password
db:
  build: images/mysql
  ports:
    - "3305:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: shorturl
    MYSQL_USER: shorturl
    MYSQL_PASSWORD: password
